name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
          matrix:
            node-version: [12, 14, 16]
            operators-system: [ubuntu-latest, windows-latest]
            include: # for only specific versions
                - node-version: 18
                  operators-system: ubuntu-latest
            exclude: # for only specific versions
                - node-version: 12
                  operators-system: windows-latest
        runs-on: ${{ matrix.operators-system }}
        steps:
          - name: Get Code
            uses: actions/checkout@v3
          - name: install nodeJS
            uses: actions/setup-node@v3
            with:
                node-version: ${{ matrix.node-version }}
          - name: Install dependencies
            run: npm ci
          - name: Build project
            run: npm run build