name: Reusable Deploy
on: 
  workflow_call:
    inputs:
        artifact-name:
            description: The name of the deployment artifact files
            required: false
            default: dist
            type: string
    outputs:
        results:
            description: The resulte of the deployment operation
            value: $ {{ jobs.deploy.outputs.outcome }}
   # secrets:
    #    some-secret:
     #       required: false
jobs:
    deploy:
        outputs:
            outcome: $ {{ steps.set-result.outputs.set-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v3
              with:
                name: $ {{ input.artifact-name }}
            - name: List files
              run: ls
            - name: Output information
              run: echo "Deploying & uploading..."
            - name: Set results output
              id: set-results
              run: echo "::set-output name=step-results::success"